#include<stdio.h>                                                                                                                                                                                                                    
#include<stdlib.h>                                                                                                                                                                                                                   
#include<unistd.h>                                                                                                                                                                                                                   
#include<string.h>                                                                                                                                                                                                                   
#include<sys/msg.h>                                                                                                                                                                                                                  
#define MAX_SIZE 512                                                                                                                                                                                                                 
struct Msg                                                                                                                                                                                                                           
{       char name[256];                                                                                                                                                                                                              
        char data[256];                                                                                                                                                                                                              
};                                                                                                                                                                                                                                   
struct MyMsg                                                                                                                                                                                                                         
{       long int msg_type;                                                                                                                                                                                                           
        struct Msg msg_body;                                                                                                                                                                                                         
};                                                                                                                                                                                                                                   
int main()                                                                                                                                                                                                                           
{       struct MyMsg msg;                                                                                                                                                                                                            
        int msgid,ch = 1 ;                                                                                                                                                                                                           
        char uname[256];                                                                                                                                                                                                             
        char cname[256];                                                                                                                                                                                                             
        printf("Enter ur name : ");                                                                                                                                                                                                  
        scanf("%s",&uname);                                                                                                                                                                                                          
        while(ch){                                                                                                                                                                                                                   
        printf("1.chat 2.view 0.exit : ");                                                                                                                                                                                           
        scanf("%d",&ch);                                                                                                                                                                                                             
        if(ch == 1)                                                                                                                                                                                                                  
        {       printf("Enter chat person name : ");                                                                                                                                                                                 
                scanf("%s",&cname);                                                                                                                                                                                                  
                msgid = msgget((key_t)uname,0666|IPC_CREAT);                                                                                                                                                                         
                msg.msg_type = 1;                                                                                                                                                                                                    
                strcpy(msg.msg_body.name,cname);                                                                                                                                                                                     
                strcpy(msg.msg_body.data,"some data");                                                                                                                                                                               
                msgsnd(msgid,(void *)&msg,MAX_SIZE,0);                                                                                                                                                                               
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        else                                                                                                                                                                                                                         
        {       msgid = msgget((key_t)uname,0666|IPC_CREAT);                                                                                                                                                                         
                msgrcv(msgid,(void *)&msg,MAX_SIZE,0,0);                                                                                                                                                                             
                printf("%s\n",msg.msg_body.name);                                                                                                                                                                                    
                printf("%s\n",msg.msg_body.data);                                                                                                                                                                                    
        }                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                            
        exit(EXIT_SUCCESS);                                                                                                                                                                                                          
                                                                                                                                                                                                                                     
}  
